#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RuntimeEventKind {
    OwnerMessageReceived,
    QueueChanged,
    CaseOpened,
    CaseResumed,
    PromptFrameRendered,
    PromptFrameSkipped,
    EndpointCallRequested,
    EndpointResponseReceived,
    EndpointFault,
    ProviderAnomaly,
    ModelActionParsed,
    ParseFault,
    ImplicitEnvelopeNormalized,
    SchemaFault,
    AdmissionRequested,
    AdmissionAccepted,
    AdmissionRefused,
    StaleActionRefused,
    RepeatedActionRefused,
    ToolStarted,
    ToolSucceeded,
    ToolFailed,
    RepeatActionDetected,
    PayloadOverflowDetected,
    EvidenceAdded,
    ArtifactPlanned,
    ArtifactRootMissing,
    ArtifactApplied,
    ArtifactAudited,
    ArtifactAuditPassed,
    ArtifactAuditFailed,
    ArtifactWeakPathFound,
    ArtifactBatchCursorAdvanced,
    VerificationRequested,
    VerificationPassed,
    VerificationFailed,
    CompletionRequested,
    CompletionAccepted,
    CompletionRefused,
    CompletionBlocked,
    CaseClosed,
    ContextPressureDetected,
    CompactionStarted,
    CompactionCompleted,
    MaintenanceTick,
    MaintenanceDue,
    MaintenanceStarted,
    MaintenanceDeferred,
    MaintenanceNoop,
    MaintenanceNoopCooldownRecorded,
    MaintenanceCompleted,
    TurnBudgetCheckpoint,
    TurnBudgetExhausted,
    OwnerInputRequired,
    BlockedHandoffRecorded,
    ClosedIdleSelected,
}

impl RuntimeEventKind {
    pub const ALL: [Self; 56] = [
        Self::OwnerMessageReceived,
        Self::QueueChanged,
        Self::CaseOpened,
        Self::CaseResumed,
        Self::PromptFrameRendered,
        Self::PromptFrameSkipped,
        Self::EndpointCallRequested,
        Self::EndpointResponseReceived,
        Self::EndpointFault,
        Self::ProviderAnomaly,
        Self::ModelActionParsed,
        Self::ParseFault,
        Self::ImplicitEnvelopeNormalized,
        Self::SchemaFault,
        Self::AdmissionRequested,
        Self::AdmissionAccepted,
        Self::AdmissionRefused,
        Self::StaleActionRefused,
        Self::RepeatedActionRefused,
        Self::ToolStarted,
        Self::ToolSucceeded,
        Self::ToolFailed,
        Self::RepeatActionDetected,
        Self::PayloadOverflowDetected,
        Self::EvidenceAdded,
        Self::ArtifactPlanned,
        Self::ArtifactRootMissing,
        Self::ArtifactApplied,
        Self::ArtifactAudited,
        Self::ArtifactAuditPassed,
        Self::ArtifactAuditFailed,
        Self::ArtifactWeakPathFound,
        Self::ArtifactBatchCursorAdvanced,
        Self::VerificationRequested,
        Self::VerificationPassed,
        Self::VerificationFailed,
        Self::CompletionRequested,
        Self::CompletionAccepted,
        Self::CompletionRefused,
        Self::CompletionBlocked,
        Self::CaseClosed,
        Self::ContextPressureDetected,
        Self::CompactionStarted,
        Self::CompactionCompleted,
        Self::MaintenanceTick,
        Self::MaintenanceDue,
        Self::MaintenanceStarted,
        Self::MaintenanceDeferred,
        Self::MaintenanceNoop,
        Self::MaintenanceNoopCooldownRecorded,
        Self::MaintenanceCompleted,
        Self::TurnBudgetCheckpoint,
        Self::TurnBudgetExhausted,
        Self::OwnerInputRequired,
        Self::BlockedHandoffRecorded,
        Self::ClosedIdleSelected,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::OwnerMessageReceived => "owner_message_received",
            Self::QueueChanged => "queue_changed",
            Self::CaseOpened => "case_opened",
            Self::CaseResumed => "case_resumed",
            Self::PromptFrameRendered => "prompt_frame_rendered",
            Self::PromptFrameSkipped => "prompt_frame_skipped",
            Self::EndpointCallRequested => "endpoint_call_requested",
            Self::EndpointResponseReceived => "endpoint_response_received",
            Self::EndpointFault => "endpoint_fault",
            Self::ProviderAnomaly => "provider_anomaly",
            Self::ModelActionParsed => "model_action_parsed",
            Self::ParseFault => "parse_fault",
            Self::ImplicitEnvelopeNormalized => "implicit_envelope_normalized",
            Self::SchemaFault => "schema_fault",
            Self::AdmissionRequested => "admission_requested",
            Self::AdmissionAccepted => "admission_accepted",
            Self::AdmissionRefused => "admission_refused",
            Self::StaleActionRefused => "stale_action_refused",
            Self::RepeatedActionRefused => "repeated_action_refused",
            Self::ToolStarted => "tool_started",
            Self::ToolSucceeded => "tool_succeeded",
            Self::ToolFailed => "tool_failed",
            Self::RepeatActionDetected => "repeat_action_detected",
            Self::PayloadOverflowDetected => "payload_overflow_detected",
            Self::EvidenceAdded => "evidence_added",
            Self::ArtifactPlanned => "artifact_planned",
            Self::ArtifactRootMissing => "artifact_root_missing",
            Self::ArtifactApplied => "artifact_applied",
            Self::ArtifactAudited => "artifact_audited",
            Self::ArtifactAuditPassed => "artifact_audit_passed",
            Self::ArtifactAuditFailed => "artifact_audit_failed",
            Self::ArtifactWeakPathFound => "artifact_weak_path_found",
            Self::ArtifactBatchCursorAdvanced => "artifact_batch_cursor_advanced",
            Self::VerificationRequested => "verification_requested",
            Self::VerificationPassed => "verification_passed",
            Self::VerificationFailed => "verification_failed",
            Self::CompletionRequested => "completion_requested",
            Self::CompletionAccepted => "completion_accepted",
            Self::CompletionRefused => "completion_refused",
            Self::CompletionBlocked => "completion_blocked",
            Self::CaseClosed => "case_closed",
            Self::ContextPressureDetected => "context_pressure_detected",
            Self::CompactionStarted => "compaction_started",
            Self::CompactionCompleted => "compaction_completed",
            Self::MaintenanceTick => "maintenance_tick",
            Self::MaintenanceDue => "maintenance_due",
            Self::MaintenanceStarted => "maintenance_started",
            Self::MaintenanceDeferred => "maintenance_deferred",
            Self::MaintenanceNoop => "maintenance_noop",
            Self::MaintenanceNoopCooldownRecorded => "maintenance_noop_cooldown_recorded",
            Self::MaintenanceCompleted => "maintenance_completed",
            Self::TurnBudgetCheckpoint => "turn_budget_checkpoint",
            Self::TurnBudgetExhausted => "turn_budget_exhausted",
            Self::OwnerInputRequired => "owner_input_required",
            Self::BlockedHandoffRecorded => "blocked_handoff_recorded",
            Self::ClosedIdleSelected => "closed_idle_selected",
        }
    }
}
