#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RuntimeEventKind {
    OwnerMessageReceived,
    QueueChanged,
    CaseOpened,
    CaseResumed,
    PromptFrameRendered,
    EndpointCallRequested,
    EndpointResponseReceived,
    EndpointFault,
    ModelActionParsed,
    ParseFault,
    SchemaFault,
    AdmissionRequested,
    AdmissionRefused,
    ToolStarted,
    ToolSucceeded,
    ToolFailed,
    RepeatActionDetected,
    PayloadOverflowDetected,
    EvidenceAdded,
    ArtifactPlanned,
    ArtifactApplied,
    ArtifactAudited,
    ArtifactWeakPathFound,
    VerificationRequested,
    VerificationPassed,
    VerificationFailed,
    CompletionRequested,
    CompletionBlocked,
    CaseClosed,
    ContextPressureDetected,
    CompactionStarted,
    CompactionCompleted,
    MaintenanceTick,
    MaintenanceStarted,
    MaintenanceNoop,
    MaintenanceCompleted,
    TurnBudgetCheckpoint,
    TurnBudgetExhausted,
    OwnerInputRequired,
    BlockedHandoffRecorded,
}

impl RuntimeEventKind {
    pub const ALL: [Self; 40] = [
        Self::OwnerMessageReceived,
        Self::QueueChanged,
        Self::CaseOpened,
        Self::CaseResumed,
        Self::PromptFrameRendered,
        Self::EndpointCallRequested,
        Self::EndpointResponseReceived,
        Self::EndpointFault,
        Self::ModelActionParsed,
        Self::ParseFault,
        Self::SchemaFault,
        Self::AdmissionRequested,
        Self::AdmissionRefused,
        Self::ToolStarted,
        Self::ToolSucceeded,
        Self::ToolFailed,
        Self::RepeatActionDetected,
        Self::PayloadOverflowDetected,
        Self::EvidenceAdded,
        Self::ArtifactPlanned,
        Self::ArtifactApplied,
        Self::ArtifactAudited,
        Self::ArtifactWeakPathFound,
        Self::VerificationRequested,
        Self::VerificationPassed,
        Self::VerificationFailed,
        Self::CompletionRequested,
        Self::CompletionBlocked,
        Self::CaseClosed,
        Self::ContextPressureDetected,
        Self::CompactionStarted,
        Self::CompactionCompleted,
        Self::MaintenanceTick,
        Self::MaintenanceStarted,
        Self::MaintenanceNoop,
        Self::MaintenanceCompleted,
        Self::TurnBudgetCheckpoint,
        Self::TurnBudgetExhausted,
        Self::OwnerInputRequired,
        Self::BlockedHandoffRecorded,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::OwnerMessageReceived => "owner_message_received",
            Self::QueueChanged => "queue_changed",
            Self::CaseOpened => "case_opened",
            Self::CaseResumed => "case_resumed",
            Self::PromptFrameRendered => "prompt_frame_rendered",
            Self::EndpointCallRequested => "endpoint_call_requested",
            Self::EndpointResponseReceived => "endpoint_response_received",
            Self::EndpointFault => "endpoint_fault",
            Self::ModelActionParsed => "model_action_parsed",
            Self::ParseFault => "parse_fault",
            Self::SchemaFault => "schema_fault",
            Self::AdmissionRequested => "admission_requested",
            Self::AdmissionRefused => "admission_refused",
            Self::ToolStarted => "tool_started",
            Self::ToolSucceeded => "tool_succeeded",
            Self::ToolFailed => "tool_failed",
            Self::RepeatActionDetected => "repeat_action_detected",
            Self::PayloadOverflowDetected => "payload_overflow_detected",
            Self::EvidenceAdded => "evidence_added",
            Self::ArtifactPlanned => "artifact_planned",
            Self::ArtifactApplied => "artifact_applied",
            Self::ArtifactAudited => "artifact_audited",
            Self::ArtifactWeakPathFound => "artifact_weak_path_found",
            Self::VerificationRequested => "verification_requested",
            Self::VerificationPassed => "verification_passed",
            Self::VerificationFailed => "verification_failed",
            Self::CompletionRequested => "completion_requested",
            Self::CompletionBlocked => "completion_blocked",
            Self::CaseClosed => "case_closed",
            Self::ContextPressureDetected => "context_pressure_detected",
            Self::CompactionStarted => "compaction_started",
            Self::CompactionCompleted => "compaction_completed",
            Self::MaintenanceTick => "maintenance_tick",
            Self::MaintenanceStarted => "maintenance_started",
            Self::MaintenanceNoop => "maintenance_noop",
            Self::MaintenanceCompleted => "maintenance_completed",
            Self::TurnBudgetCheckpoint => "turn_budget_checkpoint",
            Self::TurnBudgetExhausted => "turn_budget_exhausted",
            Self::OwnerInputRequired => "owner_input_required",
            Self::BlockedHandoffRecorded => "blocked_handoff_recorded",
        }
    }
}
