use lkjagent_tools::model_names::{
    replacement_report, sanitize_model_names, unsanitized_model_name_count,
};

#[test]
fn sanitizer_replaces_provider_tokens_and_reports_counts() {
    let raw = "# lkjagent GPT-5.5-Pro Run Log\nQwen3.5 and Claude-3 met Gemini-2.0.";
    let sanitized = sanitize_model_names(raw);

    assert!(sanitized.text.contains("# lkjagent Model Run Log"));
    assert!(sanitized.text.contains("model endpoint and model endpoint"));
    assert!(!sanitized.text.contains("GPT-5.5-Pro"));
    assert!(!sanitized.text.contains("Qwen3.5"));
    assert!(!sanitized.text.contains("Claude-3"));
    assert!(!sanitized.text.contains("Gemini-2.0"));
    assert_eq!(unsanitized_model_name_count(raw), 5);

    let report = replacement_report(&sanitized);
    assert!(report.contains("model_name_replacements=5"));
    assert!(report.contains("pattern=GPT-5.5-Pro"));
}

#[test]
fn sanitizer_rewrites_generated_summary_claims() {
    let raw = "Qwen3.5 is the latest model. Generated by the named model.";
    let sanitized = sanitize_model_names(raw);

    assert_eq!(
        sanitized.text,
        "model endpoint is the configured model. Generated by lkjagent using the configured model endpoint."
    );
}
