pub const EXTRA_ROLES: &[&str] = &[
    "overview",
    "implementation",
    "verification",
    "recovery",
    "reference",
    "runtime",
    "state model",
    "context package",
    "action protocol",
    "tool dispatch",
    "audit evidence",
    "failure mode",
    "owner workflow",
    "operator handoff",
    "data model",
    "queue behavior",
    "memory retrieval",
    "console status",
    "token ledger",
    "catalog metadata",
    "test case",
    "acceptance gate",
    "risk register",
    "decision record",
    "configuration",
    "command map",
    "troubleshooting",
    "deployment",
    "maintenance",
    "security boundary",
    "performance note",
    "open question",
    "integration path",
    "diagnostic path",
    "repair path",
    "source map",
    "glossary",
    "examples",
    "constraints",
    "non goals",
    "assumptions",
    "evidence map",
];
