#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SanitizedText {
    pub text: String,
    pub replacements: Vec<ModelNameReplacement>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModelNameReplacement {
    pub pattern: String,
    pub replacement: String,
    pub count: usize,
}

pub fn sanitize_model_names(input: &str) -> SanitizedText {
    let mut report = Vec::new();
    let mut text = replace_provider_tokens(input, &mut report);
    text = replace_phrase(&text, "latest model", "configured model", &mut report);
    text = replace_phrase(
        &text,
        "Generated by the named model",
        "Generated by lkjagent using the configured model endpoint",
        &mut report,
    );
    text = replace_phrase(
        &text,
        "configured model endpoint Run Log",
        "Model Run Log",
        &mut report,
    );
    SanitizedText {
        text,
        replacements: report,
    }
}

pub fn unsanitized_model_name_count(input: &str) -> usize {
    let sanitized = sanitize_model_names(input);
    sanitized.replacements.iter().map(|row| row.count).sum()
}

pub fn replacement_report(sanitized: &SanitizedText) -> String {
    if sanitized.replacements.is_empty() {
        return "model_name_replacements=0".to_string();
    }
    let mut lines = vec![format!(
        "model_name_replacements={}",
        sanitized
            .replacements
            .iter()
            .map(|row| row.count)
            .sum::<usize>()
    )];
    for row in &sanitized.replacements {
        lines.push(format!(
            "pattern={} replacement={} count={}",
            row.pattern, row.replacement, row.count
        ));
    }
    lines.join("\n")
}

fn replace_provider_tokens(input: &str, report: &mut Vec<ModelNameReplacement>) -> String {
    let mut output = String::new();
    let mut index = 0;
    let mut counts: Vec<(String, String, usize)> = Vec::new();
    while index < input.len() {
        if let Some((end, replacement, pattern)) = provider_match(input, index) {
            output.push_str(replacement);
            bump(&mut counts, pattern, replacement.to_string());
            index = end;
        } else if let Some(ch) = input[index..].chars().next() {
            output.push(ch);
            index += ch.len_utf8();
        } else {
            break;
        }
    }
    for (pattern, replacement, count) in counts {
        report.push(ModelNameReplacement {
            pattern,
            replacement,
            count,
        });
    }
    output
}

fn provider_match(input: &str, index: usize) -> Option<(usize, &'static str, String)> {
    if index > 0 {
        let prev = input[..index].chars().next_back()?;
        if prev.is_ascii_alphanumeric() {
            return None;
        }
    }
    for prefix in [
        "GPT", "gpt", "Qwen", "qwen", "Claude", "claude", "Gemini", "gemini",
    ] {
        if input[index..].starts_with(prefix) {
            let end = token_end(input, index + prefix.len());
            let pattern = input[index..end].to_string();
            return Some((end, replacement_for(prefix), pattern));
        }
    }
    None
}

fn token_end(input: &str, mut index: usize) -> usize {
    while let Some(ch) = input[index..].chars().next() {
        if ch.is_ascii_alphanumeric() || matches!(ch, '-' | '.' | '*') {
            index += ch.len_utf8();
        } else {
            break;
        }
    }
    index
}

fn replacement_for(prefix: &str) -> &'static str {
    if prefix.eq_ignore_ascii_case("gpt") {
        "configured model endpoint"
    } else {
        "model endpoint"
    }
}

fn replace_phrase(
    input: &str,
    pattern: &str,
    replacement: &str,
    report: &mut Vec<ModelNameReplacement>,
) -> String {
    let count = input.matches(pattern).count();
    if count == 0 {
        return input.to_string();
    }
    report.push(ModelNameReplacement {
        pattern: pattern.to_string(),
        replacement: replacement.to_string(),
        count,
    });
    input.replace(pattern, replacement)
}

fn bump(rows: &mut Vec<(String, String, usize)>, pattern: String, replacement: String) {
    if let Some(row) = rows
        .iter_mut()
        .find(|row| row.0 == pattern && row.1 == replacement)
    {
        row.2 = row.2.saturating_add(1);
    } else {
        rows.push((pattern, replacement, 1));
    }
}
