pub mod case_completion;
pub mod case_context;
pub mod case_document;
pub mod case_evidence;
pub mod case_fields;
pub mod case_objective;
pub mod case_plan;
pub mod case_recovery;
pub mod classify;
mod classify_signals;
pub mod compaction;
pub mod completion;
pub mod guards;
pub mod maintenance;
pub mod model;
pub mod policy;
pub mod render;
pub mod source;
mod source_code;
mod source_core;
mod source_docs;
mod source_edges;
mod source_maintenance;
mod source_nodes;
mod source_packages;
mod source_recovery;
pub mod state;
pub mod transition;
pub mod transition_history;
pub mod validate;

pub use classify::{classify_intent, initial_state};
pub use compaction::compaction_plan;
pub use completion::{completion_decision, missing_requirements};
pub use guards::*;
pub use model::*;
pub use policy::*;
pub use render::render_graph_slice;
pub use source::source_graph;
pub use state::*;
pub use transition::{admit_transition, admitted_targets, legal_targets};
pub use validate::{validate_graph, ValidationReport};
