pub mod classify;
mod classify_signals;
pub mod compaction;
pub mod completion;
pub mod maintenance;
pub mod model;
pub mod render;
pub mod source;
mod source_edges;
mod source_nodes;
mod source_packages;
pub mod state;
pub mod transition;
pub mod validate;

pub use classify::{classify_intent, initial_state};
pub use compaction::compaction_plan;
pub use completion::{completion_decision, missing_requirements};
pub use model::*;
pub use render::render_graph_slice;
pub use source::source_graph;
pub use state::*;
pub use transition::{admit_transition, legal_targets};
pub use validate::{validate_graph, ValidationReport};
