use crate::guards::Guard;
use crate::model::{EdgeKind, GraphEdge, GraphEdgeId, GraphNodeId, TaskFamily};
use crate::policy::ContextPressureLevel;

const ALWAYS: &[Guard] = &[Guard::Always];
const PLAN_READY: &[Guard] = &[Guard::PlanReady];
const PLAN_CONTEXT: &[Guard] = &[Guard::PlanReady, Guard::ContextSelected];
const OBSERVED: &[Guard] = &[Guard::HasEvidence("observation")];
const VERIFIED: &[Guard] = &[Guard::CompletionReady];
const DOCUMENT_FAMILIES: &[TaskFamily] = &[TaskFamily::Documentation, TaskFamily::KnowledgeBase];
const DOC_FAMILY: &[Guard] = &[Guard::PlanReady, Guard::FamilyIn(DOCUMENT_FAMILIES)];
const DOC_AUDIT: &[Guard] = &[Guard::DocumentAuditReady];
const SOFT_PRESSURE: &[Guard] = &[Guard::ContextPressureAtLeast(ContextPressureLevel::Orange)];
const HARD_PRESSURE: &[Guard] = &[Guard::ContextPressureAtLeast(ContextPressureLevel::Red)];
const TOOL_FAULT: &[Guard] = &[Guard::FaultCountAtLeast(
    crate::case_recovery::FaultKind::Tool,
    1,
)];
const PARAM_FAULT: &[Guard] = &[Guard::FaultCountAtLeast(
    crate::case_recovery::FaultKind::Params,
    1,
)];
const REPEAT_FAULT: &[Guard] = &[Guard::FaultCountAtLeast(
    crate::case_recovery::FaultKind::Repeat,
    1,
)];
const OWNER_QUESTION: &[Guard] = &[Guard::OwnerQuestionOpen];

#[rustfmt::skip]
pub(crate) const EDGES: &[GraphEdge] = &[
    edge("intake-normalize", EdgeKind::Start, "intake", "normalize-objective", ALWAYS),
    edge("normalize-constraints", EdgeKind::Plan, "normalize-objective", "extract-constraints", ALWAYS),
    edge("constraints-non-goals", EdgeKind::Plan, "extract-constraints", "extract-non-goals", ALWAYS),
    edge("non-goals-risks", EdgeKind::Plan, "extract-non-goals", "extract-risks", ALWAYS),
    edge("risks-success", EdgeKind::Plan, "extract-risks", "extract-success-criteria", ALWAYS),
    edge("success-route-family", EdgeKind::Plan, "extract-success-criteria", "route-family", ALWAYS),
    edge("route-family-blockers", EdgeKind::Plan, "route-family", "detect-blockers", ALWAYS),
    edge("route-family-benchmark", EdgeKind::Plan, "route-family", "benchmark", ALWAYS),
    edge("benchmark-verify", EdgeKind::Verify, "benchmark", "verify", OBSERVED),
    edge("blockers-survey", EdgeKind::SelectContext, "detect-blockers", "workspace-survey", ALWAYS),
    edge("constraints-route", EdgeKind::Plan, "extract-constraints", "route", ALWAYS),
    edge("route-survey", EdgeKind::SelectContext, "route", "survey", ALWAYS),
    edge("workspace-candidates", EdgeKind::SelectContext, "workspace-survey", "candidate-paths", ALWAYS),
    edge("candidates-memory", EdgeKind::SelectContext, "candidate-paths", "memory-retrieval", ALWAYS),
    edge("memory-context-select", EdgeKind::SelectContext, "memory-retrieval", "context-select", ALWAYS),
    edge("context-select-review", EdgeKind::SelectContext, "context-select", "context-review", ALWAYS),
    edge("context-review-context", EdgeKind::SelectContext, "context-review", "context", ALWAYS),
    edge("context-refresh-context", EdgeKind::SelectContext, "context-refresh", "context", ALWAYS),
    edge("survey-context", EdgeKind::SelectContext, "survey", "context", ALWAYS),
    edge("context-decompose", EdgeKind::Plan, "context", "decompose-task", ALWAYS),
    edge("decompose-draft", EdgeKind::Plan, "decompose-task", "draft-plan", ALWAYS),
    edge("draft-plan-plan", EdgeKind::Plan, "draft-plan", "plan", ALWAYS),
    edge("context-plan", EdgeKind::Plan, "context", "plan", ALWAYS),
    edge("plan-review", EdgeKind::Plan, "plan", "review-plan", PLAN_READY),
    edge("review-risk", EdgeKind::Plan, "review-plan", "risk-review", PLAN_READY),
    edge("risk-evidence", EdgeKind::Plan, "risk-review", "evidence-plan", PLAN_READY),
    edge("evidence-verification-plan", EdgeKind::Plan, "evidence-plan", "verification-plan", PLAN_READY),
    edge("verification-choose-step", EdgeKind::Plan, "verification-plan", "choose-active-step", PLAN_READY),
    edge("choose-step-execute", EdgeKind::Execute, "choose-active-step", "execute", PLAN_CONTEXT),
    edge("review-execute", EdgeKind::Execute, "review-plan", "execute", PLAN_CONTEXT),
    edge("plan-document", EdgeKind::Plan, "plan", "document", DOC_FAMILY),
    edge("document-profile", EdgeKind::Execute, "document", "document-profile", DOC_FAMILY),
    edge("doc-profile-topology", EdgeKind::Execute, "document-profile", "document-topology", DOC_FAMILY),
    edge("doc-topology-scaffold", EdgeKind::Execute, "document-topology", "document-scaffold", DOC_FAMILY),
    edge("doc-scaffold-section-plan", EdgeKind::Execute, "document-scaffold", "document-section-plan", DOC_FAMILY),
    edge("doc-section-write", EdgeKind::Execute, "document-section-plan", "document-write", DOC_FAMILY),
    edge("doc-write-audit", EdgeKind::Verify, "document-write", "document-audit", OBSERVED),
    edge("doc-audit-repair", EdgeKind::Recover, "document-audit", "document-repair", DOC_FAMILY),
    edge("doc-repair-check", EdgeKind::Verify, "document-repair", "document-completion-check", DOC_FAMILY),
    edge("document-audit", EdgeKind::Verify, "document", "document-audit", OBSERVED),
    edge("document-verify", EdgeKind::Verify, "document-audit", "verify", DOC_AUDIT),
    edge("execute-step", EdgeKind::Execute, "execute", "execute-step", PLAN_CONTEXT),
    edge("execute-code-survey", EdgeKind::Execute, "execute", "code-survey", PLAN_CONTEXT),
    edge("code-survey-design", EdgeKind::Plan, "code-survey", "code-design", PLAN_CONTEXT),
    edge("code-design-edit", EdgeKind::Execute, "code-design", "code-edit", PLAN_CONTEXT),
    edge("code-edit-review", EdgeKind::Verify, "code-edit", "code-review", OBSERVED),
    edge("code-review-verify", EdgeKind::Verify, "code-review", "code-verify", OBSERVED),
    edge("code-verify-repair", EdgeKind::Recover, "code-verify", "code-repair", TOOL_FAULT),
    edge("code-repair-edit", EdgeKind::Execute, "code-repair", "code-edit", PLAN_CONTEXT),
    edge("step-observe-result", EdgeKind::Execute, "execute-step", "observe-result", OBSERVED),
    edge("execute-observe", EdgeKind::Execute, "execute", "observe", OBSERVED),
    edge("observe-integrate", EdgeKind::Execute, "observe", "integrate-evidence", OBSERVED),
    edge("observe-result-integrate", EdgeKind::Execute, "observe-result", "integrate-evidence", OBSERVED),
    edge("integrate-advance", EdgeKind::Execute, "integrate-evidence", "advance-plan", OBSERVED),
    edge("advance-verify", EdgeKind::Verify, "advance-plan", "verify", OBSERVED),
    edge("integrate-verify", EdgeKind::Verify, "integrate-evidence", "verify", OBSERVED),
    edge("verify-focused", EdgeKind::Verify, "verify", "verify-focused", OBSERVED),
    edge("verify-doc-code-consistency", EdgeKind::Verify, "verify", "docs-code-consistency", OBSERVED),
    edge("doc-code-final", EdgeKind::Verify, "docs-code-consistency", "verify-final", VERIFIED),
    edge("focused-style", EdgeKind::Verify, "verify-focused", "verify-style", OBSERVED),
    edge("style-docs", EdgeKind::Verify, "verify-style", "verify-docs", OBSERVED),
    edge("docs-integration", EdgeKind::Verify, "verify-docs", "verify-integration", OBSERVED),
    edge("integration-final", EdgeKind::Verify, "verify-integration", "verify-final", VERIFIED),
    edge("final-audit", EdgeKind::Complete, "verify-final", "completion-audit", VERIFIED),
    edge("audit-evidence", EdgeKind::Complete, "completion-audit", "completion-evidence", VERIFIED),
    edge("evidence-memory", EdgeKind::Complete, "completion-evidence", "completion-memory", VERIFIED),
    edge("memory-complete", EdgeKind::Complete, "completion-memory", "complete", VERIFIED),
    edge("verify-complete", EdgeKind::Complete, "verify", "complete", VERIFIED),
    edge("execute-recover-generic", EdgeKind::Recover, "execute", "recover", TOOL_FAULT),
    edge("execute-recover", EdgeKind::Recover, "execute", "recover-tool", TOOL_FAULT),
    edge("recover-inspect", EdgeKind::Recover, "recover", "recover-by-state-inspection", ALWAYS),
    edge("recover-parse", EdgeKind::Recover, "recover", "recover-parse", ALWAYS),
    edge("recover-params", EdgeKind::Recover, "recover", "recover-params", ALWAYS),
    edge("recover-endpoint", EdgeKind::Recover, "recover", "recover-endpoint", ALWAYS),
    edge("recover-budget", EdgeKind::Recover, "recover", "recover-budget", ALWAYS),
    edge("recover-verification", EdgeKind::Recover, "recover", "recover-verification", ALWAYS),
    edge("recover-tool", EdgeKind::Recover, "recover", "recover-tool", ALWAYS),
    edge("recover-repeat", EdgeKind::Recover, "recover", "recover-repeat", ALWAYS),
    edge("recover-tool-plan", EdgeKind::Plan, "recover-tool", "plan", ALWAYS),
    edge("recover-tool-inspect", EdgeKind::Recover, "recover-tool", "recover-by-state-inspection", ALWAYS),
    edge("recover-repeat-plan", EdgeKind::Plan, "recover-repeat", "plan", ALWAYS),
    edge("recover-repeat-alt", EdgeKind::Recover, "recover-repeat", "recover-by-alternate-tool", ALWAYS),
    edge("recover-parse-inspect", EdgeKind::Recover, "recover-parse", "recover-by-state-inspection", ALWAYS),
    edge("recover-params-inspect", EdgeKind::Recover, "recover-params", "recover-by-state-inspection", ALWAYS),
    edge("recover-params-plan", EdgeKind::Plan, "recover-params", "plan", ALWAYS),
    edge("recover-endpoint-context", EdgeKind::Recover, "recover-endpoint", "recover-context", ALWAYS),
    edge("recover-context-refresh", EdgeKind::SelectContext, "recover-context", "context-refresh", ALWAYS),
    edge("recover-budget-smaller", EdgeKind::Recover, "recover-budget", "recover-by-smaller-scope", ALWAYS),
    edge("recover-verification-repair", EdgeKind::Recover, "recover-verification", "repair-step", ALWAYS),
    edge("inspect-alternate", EdgeKind::Recover, "recover-by-state-inspection", "recover-by-alternate-tool", ALWAYS),
    edge("alternate-smaller", EdgeKind::Recover, "recover-by-alternate-tool", "recover-by-smaller-scope", ALWAYS),
    edge("smaller-plan", EdgeKind::Plan, "recover-by-smaller-scope", "plan", ALWAYS),
    edge("alternate-shell", EdgeKind::Recover, "recover-by-alternate-tool", "recover-by-shell-escape", TOOL_FAULT),
    edge("shell-escape-plan", EdgeKind::Plan, "recover-by-shell-escape", "plan", ALWAYS),
    edge("recover-owner-question", EdgeKind::Recover, "recover", "owner-question", OWNER_QUESTION),
    edge("execute-repeat", EdgeKind::Recover, "execute", "recover-repeat", REPEAT_FAULT),
    edge("execute-params", EdgeKind::Recover, "execute", "recover-params", PARAM_FAULT),
    edge("execute-soft-compact", EdgeKind::Compact, "execute", "compact-soft", SOFT_PRESSURE),
    edge("verify-hard-compact", EdgeKind::Compact, "verify", "compact-hard", HARD_PRESSURE),
    edge("verify-escape", EdgeKind::Recover, "verify", "escape", TOOL_FAULT),
    edge("soft-compact-boundary", EdgeKind::Compact, "compact-soft", "compact-boundary", ALWAYS),
    edge("boundary-rebuild", EdgeKind::SelectContext, "compact-boundary", "rebuild-context", ALWAYS),
    edge("compact-rebuild", EdgeKind::SelectContext, "compact-soft", "rebuild-context", ALWAYS),
    edge("hard-compact-rebuild", EdgeKind::SelectContext, "compact-hard", "rebuild-context", ALWAYS),
    edge("rebuild-resume", EdgeKind::SelectContext, "rebuild-context", "resume-after-compact", ALWAYS),
    edge("resume-context", EdgeKind::SelectContext, "resume-after-compact", "context", ALWAYS),
    edge("rebuild-context", EdgeKind::SelectContext, "rebuild-context", "context", ALWAYS),
    edge("maintain-memory", EdgeKind::Maintain, "maintain", "memory", ALWAYS),
    edge("maintain-distill", EdgeKind::Maintain, "maintain", "distill-memory", ALWAYS),
    edge("maintain-policy", EdgeKind::Maintain, "maintain", "refine-graph-policy", ALWAYS),
    edge("maintain-prune", EdgeKind::Maintain, "maintain", "prune-memory", ALWAYS),
    edge("maintain-audit", EdgeKind::Maintain, "maintain", "audit-self", ALWAYS),
    edge("audit-drift", EdgeKind::Maintain, "audit-self", "repair-doc-code-drift", ALWAYS),
    edge("distill-complete", EdgeKind::Complete, "distill-memory", "complete", ALWAYS),
    edge("policy-complete", EdgeKind::Complete, "refine-graph-policy", "complete", ALWAYS),
    edge("prune-complete", EdgeKind::Complete, "prune-memory", "complete", ALWAYS),
    edge("drift-complete", EdgeKind::Complete, "repair-doc-code-drift", "complete", ALWAYS),
];

const fn edge(
    id: &'static str,
    kind: EdgeKind,
    from: &'static str,
    to: &'static str,
    guards: &'static [Guard],
) -> GraphEdge {
    GraphEdge {
        id: GraphEdgeId(id),
        kind,
        from: GraphNodeId(from),
        to: GraphNodeId(to),
        guards,
        rationale: id,
        policy: crate::node_policy::DEFAULT_EDGE_POLICY,
    }
}
