use crate::model::{ContextPackage, ContextPackageId, GraphNodeId, PackagePriority, TaskFamily};

const PLAN_NODES: &[GraphNodeId] = &[
    GraphNodeId("intake"),
    GraphNodeId("normalize-objective"),
    GraphNodeId("extract-constraints"),
    GraphNodeId("extract-non-goals"),
    GraphNodeId("extract-risks"),
    GraphNodeId("extract-success-criteria"),
    GraphNodeId("route-family"),
    GraphNodeId("detect-blockers"),
    GraphNodeId("decompose-task"),
    GraphNodeId("draft-plan"),
    GraphNodeId("plan"),
    GraphNodeId("review-plan"),
    GraphNodeId("risk-review"),
    GraphNodeId("evidence-plan"),
    GraphNodeId("verification-plan"),
    GraphNodeId("choose-active-step"),
];
const EXEC_NODES: &[GraphNodeId] = &[
    GraphNodeId("execute"),
    GraphNodeId("execute-step"),
    GraphNodeId("observe"),
    GraphNodeId("observe-result"),
    GraphNodeId("integrate-evidence"),
    GraphNodeId("repair-step"),
    GraphNodeId("advance-plan"),
    GraphNodeId("code-survey"),
    GraphNodeId("code-design"),
    GraphNodeId("code-edit"),
    GraphNodeId("code-review"),
    GraphNodeId("code-verify"),
    GraphNodeId("code-repair"),
];
const VERIFY_NODES: &[GraphNodeId] = &[
    GraphNodeId("verify"),
    GraphNodeId("verify-focused"),
    GraphNodeId("verify-style"),
    GraphNodeId("verify-docs"),
    GraphNodeId("verify-integration"),
    GraphNodeId("verify-final"),
    GraphNodeId("completion-audit"),
    GraphNodeId("completion-evidence"),
    GraphNodeId("complete"),
];
const DOC_NODES: &[GraphNodeId] = &[
    GraphNodeId("document"),
    GraphNodeId("document-profile"),
    GraphNodeId("document-topology"),
    GraphNodeId("document-scaffold"),
    GraphNodeId("document-section-plan"),
    GraphNodeId("document-write"),
    GraphNodeId("document-audit"),
    GraphNodeId("document-repair"),
    GraphNodeId("document-completion-check"),
];
const RECOVERY_NODES: &[GraphNodeId] = &[
    GraphNodeId("recover"),
    GraphNodeId("recover-parse"),
    GraphNodeId("recover-params"),
    GraphNodeId("recover-tool"),
    GraphNodeId("recover-repeat"),
    GraphNodeId("recover-endpoint"),
    GraphNodeId("recover-context"),
    GraphNodeId("recover-budget"),
    GraphNodeId("recover-verification"),
    GraphNodeId("recover-by-state-inspection"),
    GraphNodeId("recover-by-alternate-tool"),
    GraphNodeId("recover-by-smaller-scope"),
    GraphNodeId("recover-by-shell-escape"),
    GraphNodeId("owner-question"),
];
const COMPACT_NODES: &[GraphNodeId] = &[
    GraphNodeId("compact-soft"),
    GraphNodeId("compact-hard"),
    GraphNodeId("compact-boundary"),
    GraphNodeId("rebuild-context"),
    GraphNodeId("resume-after-compact"),
];
const MAINT_NODES: &[GraphNodeId] = &[GraphNodeId("maintain"), GraphNodeId("refine-graph-policy")];
const ALL_FAMILIES: &[TaskFamily] = &[
    TaskFamily::CodeChange,
    TaskFamily::Documentation,
    TaskFamily::Maintenance,
    TaskFamily::BugFix,
    TaskFamily::Architecture,
    TaskFamily::Benchmark,
    TaskFamily::KnowledgeBase,
    TaskFamily::Verification,
    TaskFamily::Recovery,
    TaskFamily::Compaction,
    TaskFamily::IdleMaintenance,
];
const DOC_FAMILIES: &[TaskFamily] = &[TaskFamily::Documentation, TaskFamily::KnowledgeBase];

pub(crate) const PACKAGES: &[ContextPackage] = &[
    package(
        "planning-checklist",
        "Planning checklist",
        "Before mutation, normalize objective, constraints, assumptions, risks, steps, evidence, checks, and paths.",
        PLAN_NODES,
        ALL_FAMILIES,
        PackagePriority::Core,
    ),
    package(
        "context-slice",
        "Context slice",
        "Load only candidate files, relevant docs, memory hits, and workspace summary selected by the active graph node.",
        PLAN_NODES,
        ALL_FAMILIES,
        PackagePriority::Core,
    ),
    package(
        "execution-order",
        "Execution order",
        "Execute one active step, observe, bind evidence, update touched paths, then advance or recover.",
        EXEC_NODES,
        ALL_FAMILIES,
        PackagePriority::Helpful,
    ),
    package(
        "verification-gate",
        "Verification gate",
        "Completion needs plan, observation, verification when code changed, pending checks clear, and agent.done admission.",
        VERIFY_NODES,
        ALL_FAMILIES,
        PackagePriority::Core,
    ),
    package(
        "doc-construction",
        "Document construction",
        "Use doc.scaffold/doc.audit or bounded batch writes; keep README indexes, topology, coverage, and counts auditable.",
        DOC_NODES,
        DOC_FAMILIES,
        PackagePriority::Core,
    ),
    package(
        "recovery-policy",
        "Recovery policy",
        "Do not repeat failed action fingerprints; choose a different tool class and record the safer branch.",
        RECOVERY_NODES,
        ALL_FAMILIES,
        PackagePriority::Recovery,
    ),
    package(
        "compaction-preserve",
        "Compaction preservation",
        "Preserve objective, constraints, plan steps, selected packages, evidence, touched paths, recovery, and completion guard.",
        COMPACT_NODES,
        ALL_FAMILIES,
        PackagePriority::Recovery,
    ),
    package(
        "maintenance-loop",
        "Maintenance loop",
        "Idle work records graph policy, context package, memory, and audit candidates without editing source files.",
        MAINT_NODES,
        ALL_FAMILIES,
        PackagePriority::Helpful,
    ),
];

const fn package(
    id: &'static str,
    title: &'static str,
    body: &'static str,
    applies_to: &'static [GraphNodeId],
    families: &'static [TaskFamily],
    priority: PackagePriority,
) -> ContextPackage {
    ContextPackage {
        id: ContextPackageId(id),
        title,
        purpose: title,
        body,
        default_budget: 160,
        priority,
        applies_to,
        families,
    }
}
