#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TuiEvent {
    UserInputChanged(String),
    UserSubmit,
    UserInterrupt,
    UserApproveTool,
    UserRejectTool(String),
    UserOpenPalette,
    UserCloseModal,
    AgentTextDelta(String),
    AgentMessageComplete,
    ToolCallProposed { name: String, decision_id: String },
    ToolCallStarted(String),
    ToolCallFinished(String),
    StateTransitionObserved(String),
    ArtifactCreated(String),
    WorkspaceChanged(String),
    TimerTick,
    TerminalResize { width: u16, height: u16 },
    ErrorObserved(String),
    SaveTranscript,
    QuitRequested,
}
